input {
  file {
    path => "/var/log/auth.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "linux_auth"
  }
  beats {
    port => 5044
  }
}

filter {
  if [type] == "linux_auth" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} %{WORD:program}: %{GREEDYDATA:log_message}" }
   
    }
  }
  if [agent][type] == "winlogbeat" {
    if [event][code] == "4624" {
      mutate { add_field => { "event.outcome" => "success"} }
    }
    if [event][code] == "4625" {
      mutate { add_field => { "event.outcome" => "failure" } }
    }
    mutate {
      add_field => { "source.ip" => "%{[winlog][event_data][IpAddress]}" }
      add_field => { "user.name" => "%{[winlog][event_data][TargetUserName]}" }
    }
  }
}
output {
  if [type] == "linux_auth" {
    elasticsearch {
      hosts => ["localhost:9200"]
      index => "siem-logs-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "${ES_PWD}"
    }
  }
  if [agent][type] =="winlogbeat"{
    elasticsearch {
      hosts => ["localhost:9200"]
      index => "siem-windows-%{+YYYY.MM.dd}"
      user => "elastic"
      password => "${ES_PWD}"
    }
  }
}
