input {
  file {
    path => "/var/log/auth.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "linux_auth"
 }
}

filter {
  grok {
    match => { "message" => "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:host} %
{WORD:program}: %{GREEDYDATA:log_message}" }
   
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "siem-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "${ES_PWD}"
  }
}
